 

<?php include ( '../includes/_header.php'); ?>
<?php include ('_nav.php'); ?>
    <div class="container">
      <!-- Row Start -->
      <div class="row">
        <!-- Col9 start -->
        <div class="col9">
          <!-- island start -->
          <section class="island outset">
            <h1>Patient Contact Hours</h1> 
            <fieldset>
              <div class="control-group">
                <p class="label group-title">Cardiology – General</p>
              </div>
              <div class="control-group control-group-horizontal"><label>Average Patient Contact Hours per Physician per Year&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Average Patient Contact Hours per Physician per Year" data-modal-html="<p>  Please indicate the average number of direct patient contact hours a physician in this department has per year (based on a 1.0 clinical FTE). This should not represent only the minimum number of hours required. This would include time in the office seeing patients or in surgery. Any time allowed for record keeping, dictation or general catch-up work would not be included.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
              <div class="control-group control-group-horizontal"><label>Patient Contact Hours per Week&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Patient Contact Hours per Week" data-modal-html="<p>  Please indicate the number of direct patient contact hours a physician in this department has per week (based on a 1.0 clinical FTE). This should not represent only the minimum number of hours required. This would include time in the office seeing patients or in surgery during a typical full work week. Any time allowed for record keeping, dictation or general catch-up work would not be included.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
              <div class="control-group control-group-horizontal"><label>Patient Contact Days per Week&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Patient Contact Days per Week" data-modal-html="<p>  Please indicate the number of direct patient contact days a physician in this department has per week (based on a 1.0 clinical FTE). This should not represent only the minimum number of days required. This would include time in the office seeing patients or in surgery during a typical full work week. Any time allowed for record keeping, dictation or general catch-up work would not be included.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
              <div class="control-group control-group-horizontal"><label>Average Office Hours per Week&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Average Office Hours per Week" data-modal-html="<p>  Please indicate the average number of office hours a physician in this department has per week (based on a 1.0 clinical FTE). This would include any time allowed for record keeping, dictation or general catch-up work. Note: this does not include any time where the physician is on call.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
            </fieldset>
            <fieldset>
              <div class="control-group">
                <p class="label group-title">Critical Care Medicine</p>
              </div>
              <div class="control-group control-group-horizontal"><label>Average Patient Contact Hours per Physician per Year&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Average Patient Contact Hours per Physician per Year" data-modal-html="<p>  Please indicate the average number of direct patient contact hours a physician in this department has per year (based on a 1.0 clinical FTE). This should not represent only the minimum number of hours required. This would include time in the office seeing patients or in surgery. Any time allowed for record keeping, dictation or general catch-up work would not be included.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
              <div class="control-group control-group-horizontal"><label>Patient Contact Hours per Week&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Patient Contact Hours per Week" data-modal-html="<p>  Please indicate the number of direct patient contact hours a physician in this department has per week (based on a 1.0 clinical FTE). This should not represent only the minimum number of hours required. This would include time in the office seeing patients or in surgery during a typical full work week. Any time allowed for record keeping, dictation or general catch-up work would not be included.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
              <div class="control-group control-group-horizontal"><label>Patient Contact Days per Week&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Patient Contact Days per Week" data-modal-html="<p>  Please indicate the number of direct patient contact days a physician in this department has per week (based on a 1.0 clinical FTE). This should not represent only the minimum number of days required. This would include time in the office seeing patients or in surgery during a typical full work week. Any time allowed for record keeping, dictation or general catch-up work would not be included.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
              <div class="control-group control-group-horizontal"><label>Average Office Hours per Week&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Average Office Hours per Week" data-modal-html="<p>  Please indicate the average number of office hours a physician in this department has per week (based on a 1.0 clinical FTE). This would include any time allowed for record keeping, dictation or general catch-up work. Note: this does not include any time where the physician is on call.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
            </fieldset>
            <fieldset>
              <div class="control-group">
                <p class="label group-title">Dermatology</p>
              </div>
              <div class="control-group control-group-horizontal"><label>Average Patient Contact Hours per Physician per Year&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Average Patient Contact Hours per Physician per Year" data-modal-html="<p>  Please indicate the average number of direct patient contact hours a physician in this department has per year (based on a 1.0 clinical FTE). This should not represent only the minimum number of hours required. This would include time in the office seeing patients or in surgery. Any time allowed for record keeping, dictation or general catch-up work would not be included.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
              <div class="control-group control-group-horizontal"><label>Patient Contact Hours per Week&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Patient Contact Hours per Week" data-modal-html="<p>  Please indicate the number of direct patient contact hours a physician in this department has per week (based on a 1.0 clinical FTE). This should not represent only the minimum number of hours required. This would include time in the office seeing patients or in surgery during a typical full work week. Any time allowed for record keeping, dictation or general catch-up work would not be included.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
              <div class="control-group control-group-horizontal"><label>Patient Contact Days per Week&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Patient Contact Days per Week" data-modal-html="<p>  Please indicate the number of direct patient contact days a physician in this department has per week (based on a 1.0 clinical FTE). This should not represent only the minimum number of days required. This would include time in the office seeing patients or in surgery during a typical full work week. Any time allowed for record keeping, dictation or general catch-up work would not be included.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
              <div class="control-group control-group-horizontal"><label>Average Office Hours per Week&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Average Office Hours per Week" data-modal-html="<p>  Please indicate the average number of office hours a physician in this department has per week (based on a 1.0 clinical FTE). This would include any time allowed for record keeping, dictation or general catch-up work. Note: this does not include any time where the physician is on call.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
            </fieldset>
            <fieldset>
              <div class="control-group">
                <p class="label group-title">Emergency Care</p>
              </div>
              <div class="control-group control-group-horizontal"><label>Average Patient Contact Hours per Physician per Year&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Average Patient Contact Hours per Physician per Year" data-modal-html="<p>  Please indicate the average number of direct patient contact hours a physician in this department has per year (based on a 1.0 clinical FTE). This should not represent only the minimum number of hours required. This would include time in the office seeing patients or in surgery. Any time allowed for record keeping, dictation or general catch-up work would not be included.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
              <div class="control-group control-group-horizontal"><label>Patient Contact Hours per Week&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Patient Contact Hours per Week" data-modal-html="<p>  Please indicate the number of direct patient contact hours a physician in this department has per week (based on a 1.0 clinical FTE). This should not represent only the minimum number of hours required. This would include time in the office seeing patients or in surgery during a typical full work week. Any time allowed for record keeping, dictation or general catch-up work would not be included.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
              <div class="control-group control-group-horizontal"><label>Patient Contact Days per Week&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Patient Contact Days per Week" data-modal-html="<p>  Please indicate the number of direct patient contact days a physician in this department has per week (based on a 1.0 clinical FTE). This should not represent only the minimum number of days required. This would include time in the office seeing patients or in surgery during a typical full work week. Any time allowed for record keeping, dictation or general catch-up work would not be included.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
              <div class="control-group control-group-horizontal"><label>Average Office Hours per Week&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Average Office Hours per Week" data-modal-html="<p>  Please indicate the average number of office hours a physician in this department has per week (based on a 1.0 clinical FTE). This would include any time allowed for record keeping, dictation or general catch-up work. Note: this does not include any time where the physician is on call.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
            </fieldset>
            <fieldset>
              <div class="control-group">
                <p class="label group-title">Family Medicine</p>
              </div>
              <div class="control-group control-group-horizontal"><label>Average Patient Contact Hours per Physician per Year&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Average Patient Contact Hours per Physician per Year" data-modal-html="<p>  Please indicate the average number of direct patient contact hours a physician in this department has per year (based on a 1.0 clinical FTE). This should not represent only the minimum number of hours required. This would include time in the office seeing patients or in surgery. Any time allowed for record keeping, dictation or general catch-up work would not be included.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
              <div class="control-group control-group-horizontal"><label>Patient Contact Hours per Week&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Patient Contact Hours per Week" data-modal-html="<p>  Please indicate the number of direct patient contact hours a physician in this department has per week (based on a 1.0 clinical FTE). This should not represent only the minimum number of hours required. This would include time in the office seeing patients or in surgery during a typical full work week. Any time allowed for record keeping, dictation or general catch-up work would not be included.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
              <div class="control-group control-group-horizontal"><label>Patient Contact Days per Week&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Patient Contact Days per Week" data-modal-html="<p>  Please indicate the number of direct patient contact days a physician in this department has per week (based on a 1.0 clinical FTE). This should not represent only the minimum number of days required. This would include time in the office seeing patients or in surgery during a typical full work week. Any time allowed for record keeping, dictation or general catch-up work would not be included.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
              <div class="control-group control-group-horizontal"><label>Average Office Hours per Week&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Average Office Hours per Week" data-modal-html="<p>  Please indicate the average number of office hours a physician in this department has per week (based on a 1.0 clinical FTE). This would include any time allowed for record keeping, dictation or general catch-up work. Note: this does not include any time where the physician is on call.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
            </fieldset>
            <fieldset>
              <div class="control-group">
                <p class="label group-title">Gastroenterology</p>
              </div>
              <div class="control-group control-group-horizontal"><label>Average Patient Contact Hours per Physician per Year&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Average Patient Contact Hours per Physician per Year" data-modal-html="<p>  Please indicate the average number of direct patient contact hours a physician in this department has per year (based on a 1.0 clinical FTE). This should not represent only the minimum number of hours required. This would include time in the office seeing patients or in surgery. Any time allowed for record keeping, dictation or general catch-up work would not be included.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
              <div class="control-group control-group-horizontal"><label>Patient Contact Hours per Week&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Patient Contact Hours per Week" data-modal-html="<p>  Please indicate the number of direct patient contact hours a physician in this department has per week (based on a 1.0 clinical FTE). This should not represent only the minimum number of hours required. This would include time in the office seeing patients or in surgery during a typical full work week. Any time allowed for record keeping, dictation or general catch-up work would not be included.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
              <div class="control-group control-group-horizontal"><label>Patient Contact Days per Week&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Patient Contact Days per Week" data-modal-html="<p>  Please indicate the number of direct patient contact days a physician in this department has per week (based on a 1.0 clinical FTE). This should not represent only the minimum number of days required. This would include time in the office seeing patients or in surgery during a typical full work week. Any time allowed for record keeping, dictation or general catch-up work would not be included.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
              <div class="control-group control-group-horizontal"><label>Average Office Hours per Week&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Average Office Hours per Week" data-modal-html="<p>  Please indicate the average number of office hours a physician in this department has per week (based on a 1.0 clinical FTE). This would include any time allowed for record keeping, dictation or general catch-up work. Note: this does not include any time where the physician is on call.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
            </fieldset>
            <fieldset>
              <div class="control-group">
                <p class="label group-title">General Surgery</p>
              </div>
              <div class="control-group control-group-horizontal"><label>Average Patient Contact Hours per Physician per Year&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Average Patient Contact Hours per Physician per Year" data-modal-html="<p>  Please indicate the average number of direct patient contact hours a physician in this department has per year (based on a 1.0 clinical FTE). This should not represent only the minimum number of hours required. This would include time in the office seeing patients or in surgery. Any time allowed for record keeping, dictation or general catch-up work would not be included.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
              <div class="control-group control-group-horizontal"><label>Patient Contact Hours per Week&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Patient Contact Hours per Week" data-modal-html="<p>  Please indicate the number of direct patient contact hours a physician in this department has per week (based on a 1.0 clinical FTE). This should not represent only the minimum number of hours required. This would include time in the office seeing patients or in surgery during a typical full work week. Any time allowed for record keeping, dictation or general catch-up work would not be included.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
              <div class="control-group control-group-horizontal"><label>Patient Contact Days per Week&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Patient Contact Days per Week" data-modal-html="<p>  Please indicate the number of direct patient contact days a physician in this department has per week (based on a 1.0 clinical FTE). This should not represent only the minimum number of days required. This would include time in the office seeing patients or in surgery during a typical full work week. Any time allowed for record keeping, dictation or general catch-up work would not be included.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
              <div class="control-group control-group-horizontal"><label>Average Office Hours per Week&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Average Office Hours per Week" data-modal-html="<p>  Please indicate the average number of office hours a physician in this department has per week (based on a 1.0 clinical FTE). This would include any time allowed for record keeping, dictation or general catch-up work. Note: this does not include any time where the physician is on call.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
            </fieldset>
            <fieldset>
              <div class="control-group">
                <p class="label group-title">Hematology and Medical Oncology</p>
              </div>
              <div class="control-group control-group-horizontal"><label>Average Patient Contact Hours per Physician per Year&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Average Patient Contact Hours per Physician per Year" data-modal-html="<p>  Please indicate the average number of direct patient contact hours a physician in this department has per year (based on a 1.0 clinical FTE). This should not represent only the minimum number of hours required. This would include time in the office seeing patients or in surgery. Any time allowed for record keeping, dictation or general catch-up work would not be included.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
              <div class="control-group control-group-horizontal"><label>Patient Contact Hours per Week&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Patient Contact Hours per Week" data-modal-html="<p>  Please indicate the number of direct patient contact hours a physician in this department has per week (based on a 1.0 clinical FTE). This should not represent only the minimum number of hours required. This would include time in the office seeing patients or in surgery during a typical full work week. Any time allowed for record keeping, dictation or general catch-up work would not be included.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
              <div class="control-group control-group-horizontal"><label>Patient Contact Days per Week&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Patient Contact Days per Week" data-modal-html="<p>  Please indicate the number of direct patient contact days a physician in this department has per week (based on a 1.0 clinical FTE). This should not represent only the minimum number of days required. This would include time in the office seeing patients or in surgery during a typical full work week. Any time allowed for record keeping, dictation or general catch-up work would not be included.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
              <div class="control-group control-group-horizontal"><label>Average Office Hours per Week&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Average Office Hours per Week" data-modal-html="<p>  Please indicate the average number of office hours a physician in this department has per week (based on a 1.0 clinical FTE). This would include any time allowed for record keeping, dictation or general catch-up work. Note: this does not include any time where the physician is on call.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
            </fieldset>
            <fieldset>
              <div class="control-group">
                <p class="label group-title">Hospitalist – Internal Medicine</p>
              </div>
              <div class="control-group control-group-horizontal"><label>Average Patient Contact Hours per Physician per Year&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Average Patient Contact Hours per Physician per Year" data-modal-html="<p>  Please indicate the average number of direct patient contact hours a physician in this department has per year (based on a 1.0 clinical FTE). This should not represent only the minimum number of hours required. This would include time in the office seeing patients or in surgery. Any time allowed for record keeping, dictation or general catch-up work would not be included.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
              <div class="control-group control-group-horizontal"><label>Patient Contact Hours per Week&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Patient Contact Hours per Week" data-modal-html="<p>  Please indicate the number of direct patient contact hours a physician in this department has per week (based on a 1.0 clinical FTE). This should not represent only the minimum number of hours required. This would include time in the office seeing patients or in surgery during a typical full work week. Any time allowed for record keeping, dictation or general catch-up work would not be included.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
              <div class="control-group control-group-horizontal"><label>Patient Contact Days per Week&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Patient Contact Days per Week" data-modal-html="<p>  Please indicate the number of direct patient contact days a physician in this department has per week (based on a 1.0 clinical FTE). This should not represent only the minimum number of days required. This would include time in the office seeing patients or in surgery during a typical full work week. Any time allowed for record keeping, dictation or general catch-up work would not be included.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
              <div class="control-group control-group-horizontal"><label>Average Office Hours per Week&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Average Office Hours per Week" data-modal-html="<p>  Please indicate the average number of office hours a physician in this department has per week (based on a 1.0 clinical FTE). This would include any time allowed for record keeping, dictation or general catch-up work. Note: this does not include any time where the physician is on call.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
            </fieldset>
            <fieldset>
              <div class="control-group">
                <p class="label group-title">Internal Medicine</p>
              </div>
              <div class="control-group control-group-horizontal"><label>Average Patient Contact Hours per Physician per Year&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Average Patient Contact Hours per Physician per Year" data-modal-html="<p>  Please indicate the average number of direct patient contact hours a physician in this department has per year (based on a 1.0 clinical FTE). This should not represent only the minimum number of hours required. This would include time in the office seeing patients or in surgery. Any time allowed for record keeping, dictation or general catch-up work would not be included.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
              <div class="control-group control-group-horizontal"><label>Patient Contact Hours per Week&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Patient Contact Hours per Week" data-modal-html="<p>  Please indicate the number of direct patient contact hours a physician in this department has per week (based on a 1.0 clinical FTE). This should not represent only the minimum number of hours required. This would include time in the office seeing patients or in surgery during a typical full work week. Any time allowed for record keeping, dictation or general catch-up work would not be included.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
              <div class="control-group control-group-horizontal"><label>Patient Contact Days per Week&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Patient Contact Days per Week" data-modal-html="<p>  Please indicate the number of direct patient contact days a physician in this department has per week (based on a 1.0 clinical FTE). This should not represent only the minimum number of days required. This would include time in the office seeing patients or in surgery during a typical full work week. Any time allowed for record keeping, dictation or general catch-up work would not be included.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
              <div class="control-group control-group-horizontal"><label>Average Office Hours per Week&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Average Office Hours per Week" data-modal-html="<p>  Please indicate the average number of office hours a physician in this department has per week (based on a 1.0 clinical FTE). This would include any time allowed for record keeping, dictation or general catch-up work. Note: this does not include any time where the physician is on call.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
            </fieldset>
            <fieldset>
              <div class="control-group">
                <p class="label group-title">Neurological Surgery</p>
              </div>
              <div class="control-group control-group-horizontal"><label>Average Patient Contact Hours per Physician per Year&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Average Patient Contact Hours per Physician per Year" data-modal-html="<p>  Please indicate the average number of direct patient contact hours a physician in this department has per year (based on a 1.0 clinical FTE). This should not represent only the minimum number of hours required. This would include time in the office seeing patients or in surgery. Any time allowed for record keeping, dictation or general catch-up work would not be included.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
              <div class="control-group control-group-horizontal"><label>Patient Contact Hours per Week&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Patient Contact Hours per Week" data-modal-html="<p>  Please indicate the number of direct patient contact hours a physician in this department has per week (based on a 1.0 clinical FTE). This should not represent only the minimum number of hours required. This would include time in the office seeing patients or in surgery during a typical full work week. Any time allowed for record keeping, dictation or general catch-up work would not be included.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
              <div class="control-group control-group-horizontal"><label>Patient Contact Days per Week&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Patient Contact Days per Week" data-modal-html="<p>  Please indicate the number of direct patient contact days a physician in this department has per week (based on a 1.0 clinical FTE). This should not represent only the minimum number of days required. This would include time in the office seeing patients or in surgery during a typical full work week. Any time allowed for record keeping, dictation or general catch-up work would not be included.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
              <div class="control-group control-group-horizontal"><label>Average Office Hours per Week&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Average Office Hours per Week" data-modal-html="<p>  Please indicate the average number of office hours a physician in this department has per week (based on a 1.0 clinical FTE). This would include any time allowed for record keeping, dictation or general catch-up work. Note: this does not include any time where the physician is on call.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
            </fieldset>
            <fieldset>
              <div class="control-group">
                <p class="label group-title">OB/GYN – General</p>
              </div>
              <div class="control-group control-group-horizontal"><label>Average Patient Contact Hours per Physician per Year&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-htmldalAverage Patient Contact Hours per Physician per Year-title="" data-modal-html="">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
              <div class="control-group control-group-horizontal"><label>Patient Contact Hours per Week&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Patient Contact Hours per Week" data-modal-html="">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
              <div class="control-group control-group-horizontal"><label>Patient Contact Days per Week&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Patient Contact Days per Week" data-modal-html="">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
              <div class="control-group control-group-horizontal"><label>Average Office Hours per Week&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Average Office Hours per Week" data-modal-html="">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
            </fieldset>
            <fieldset>
              <div class="control-group">
                <p class="label group-title">Ophthalmology</p>
              </div>
              <div class="control-group control-group-horizontal"><label>Average Patient Contact Hours per Physician per Year&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Average Patient Contact Hours per Physician per Year" data-modal-html="<p>  Please indicate the average number of direct patient contact hours a physician in this department has per year (based on a 1.0 clinical FTE). This should not represent only the minimum number of hours required. This would include time in the office seeing patients or in surgery. Any time allowed for record keeping, dictation or general catch-up work would not be included.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
              <div class="control-group control-group-horizontal"><label>Patient Contact Hours per Week&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Patient Contact Hours per Week" data-modal-html="<p>  Please indicate the number of direct patient contact hours a physician in this department has per week (based on a 1.0 clinical FTE). This should not represent only the minimum number of hours required. This would include time in the office seeing patients or in surgery during a typical full work week. Any time allowed for record keeping, dictation or general catch-up work would not be included.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
              <div class="control-group control-group-horizontal"><label>Patient Contact Days per Week&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Patient Contact Days per Week" data-modal-html="<p>  Please indicate the number of direct patient contact days a physician in this department has per week (based on a 1.0 clinical FTE). This should not represent only the minimum number of days required. This would include time in the office seeing patients or in surgery during a typical full work week. Any time allowed for record keeping, dictation or general catch-up work would not be included.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
              <div class="control-group control-group-horizontal"><label>Average Office Hours per Week&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Average Office Hours per Week" data-modal-html="<p>  Please indicate the average number of office hours a physician in this department has per week (based on a 1.0 clinical FTE). This would include any time allowed for record keeping, dictation or general catch-up work. Note: this does not include any time where the physician is on call.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
            </fieldset>
            <fieldset>
              <div class="control-group">
                <p class="label group-title">Otolaryngology</p>
              </div>
              <div class="control-group control-group-horizontal"><label>Average Patient Contact Hours per Physician per Year&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Average Patient Contact Hours per Physician per Year" data-modal-html="<p>  Please indicate the average number of direct patient contact hours a physician in this department has per year (based on a 1.0 clinical FTE). This should not represent only the minimum number of hours required. This would include time in the office seeing patients or in surgery. Any time allowed for record keeping, dictation or general catch-up work would not be included.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
              <div class="control-group control-group-horizontal"><label>Patient Contact Hours per Week&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Patient Contact Hours per Week" data-modal-html="<p>  Please indicate the number of direct patient contact hours a physician in this department has per week (based on a 1.0 clinical FTE). This should not represent only the minimum number of hours required. This would include time in the office seeing patients or in surgery during a typical full work week. Any time allowed for record keeping, dictation or general catch-up work would not be included.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
              <div class="control-group control-group-horizontal"><label>Patient Contact Days per Week&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Patient Contact Days per Week" data-modal-html="<p>  Please indicate the number of direct patient contact days a physician in this department has per week (based on a 1.0 clinical FTE). This should not represent only the minimum number of days required. This would include time in the office seeing patients or in surgery during a typical full work week. Any time allowed for record keeping, dictation or general catch-up work would not be included.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
              <div class="control-group control-group-horizontal"><label>Average Office Hours per Week&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Average Office Hours per Week" data-modal-html="<p>  Please indicate the average number of office hours a physician in this department has per week (based on a 1.0 clinical FTE). This would include any time allowed for record keeping, dictation or general catch-up work. Note: this does not include any time where the physician is on call.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
            </fieldset>
            <fieldset>
              <div class="control-group">
                <p class="label group-title">Pediatrics – General</p>
              </div>
              <div class="control-group control-group-horizontal"><label>Average Patient Contact Hours per Physician per Year&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Average Patient Contact Hours per Physician per Year" data-modal-html="<p>  Please indicate the average number of direct patient contact hours a physician in this department has per year (based on a 1.0 clinical FTE). This should not represent only the minimum number of hours required. This would include time in the office seeing patients or in surgery. Any time allowed for record keeping, dictation or general catch-up work would not be included.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
              <div class="control-group control-group-horizontal"><label>Patient Contact Hours per Week&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Patient Contact Hours per Week" data-modal-html="<p>  Please indicate the number of direct patient contact hours a physician in this department has per week (based on a 1.0 clinical FTE). This should not represent only the minimum number of hours required. This would include time in the office seeing patients or in surgery during a typical full work week. Any time allowed for record keeping, dictation or general catch-up work would not be included.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
              <div class="control-group control-group-horizontal"><label>Patient Contact Days per Week&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Patient Contact Days per Week" data-modal-html="<p>  Please indicate the number of direct patient contact days a physician in this department has per week (based on a 1.0 clinical FTE). This should not represent only the minimum number of days required. This would include time in the office seeing patients or in surgery during a typical full work week. Any time allowed for record keeping, dictation or general catch-up work would not be included.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
              <div class="control-group control-group-horizontal"><label>Average Office Hours per Week&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Average Office Hours per Week" data-modal-html="<p>  Please indicate the average number of office hours a physician in this department has per week (based on a 1.0 clinical FTE). This would include any time allowed for record keeping, dictation or general catch-up work. Note: this does not include any time where the physician is on call.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
            </fieldset>
            <fieldset>
              <div class="control-group">
                <p class="label group-title">Urgent Care</p>
              </div>
              <div class="control-group control-group-horizontal"><label>Average Patient Contact Hours per Physician per Year&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Average Patient Contact Hours per Physician per Year" data-modal-html="<p>  Please indicate the average number of direct patient contact hours a physician in this department has per year (based on a 1.0 clinical FTE). This should not represent only the minimum number of hours required. This would include time in the office seeing patients or in surgery. Any time allowed for record keeping, dictation or general catch-up work would not be included.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
              <div class="control-group control-group-horizontal"><label>Patient Contact Hours per Week&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Patient Contact Hours per Week" data-modal-html="<p>  Please indicate the number of direct patient contact hours a physician in this department has per week (based on a 1.0 clinical FTE). This should not represent only the minimum number of hours required. This would include time in the office seeing patients or in surgery during a typical full work week. Any time allowed for record keeping, dictation or general catch-up work would not be included.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
              <div class="control-group control-group-horizontal"><label>Patient Contact Days per Week&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Patient Contact Days per Week" data-modal-html="<p>  Please indicate the number of direct patient contact days a physician in this department has per week (based on a 1.0 clinical FTE). This should not represent only the minimum number of days required. This would include time in the office seeing patients or in surgery during a typical full work week. Any time allowed for record keeping, dictation or general catch-up work would not be included.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
              <div class="control-group control-group-horizontal"><label>Average Office Hours per Week&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Average Office Hours per Week" data-modal-html="<p>  Please indicate the average number of office hours a physician in this department has per week (based on a 1.0 clinical FTE). This would include any time allowed for record keeping, dictation or general catch-up work. Note: this does not include any time where the physician is on call.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
            </fieldset>
            <fieldset>
              <div class="control-group">
                <p class="label group-title">Urology</p>
              </div>
              <div class="control-group control-group-horizontal"><label>Average Patient Contact Hours per Physician per Year&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Average Patient Contact Hours per Physician per Year" data-modal-html="<p>  Please indicate the average number of direct patient contact hours a physician in this department has per year (based on a 1.0 clinical FTE). This should not represent only the minimum number of hours required. This would include time in the office seeing patients or in surgery. Any time allowed for record keeping, dictation or general catch-up work would not be included.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
              <div class="control-group control-group-horizontal"><label>Patient Contact Hours per Week&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Patient Contact Hours per Week" data-modal-html="<p>  Please indicate the number of direct patient contact hours a physician in this department has per week (based on a 1.0 clinical FTE). This should not represent only the minimum number of hours required. This would include time in the office seeing patients or in surgery during a typical full work week. Any time allowed for record keeping, dictation or general catch-up work would not be included.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
              <div class="control-group control-group-horizontal"><label>Patient Contact Days per Week&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Patient Contact Days per Week" data-modal-html="<p>  Please indicate the number of direct patient contact days a physician in this department has per week (based on a 1.0 clinical FTE). This should not represent only the minimum number of days required. This would include time in the office seeing patients or in surgery during a typical full work week. Any time allowed for record keeping, dictation or general catch-up work would not be included.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
              <div class="control-group control-group-horizontal"><label>Average Office Hours per Week&nbsp;<a tabindex="-1" href="#modal" data-toggle="modal" data-modal-title="Average Office Hours per Week" data-modal-html="<p>  Please indicate the average number of office hours a physician in this department has per week (based on a 1.0 clinical FTE). This would include any time allowed for record keeping, dictation or general catch-up work. Note: this does not include any time where the physician is on call.</p>">(?)</a></label><input type="text" data-type="number" data-validate="float" data-validate-min="0" data-validate-max="999"></div>
            </fieldset>
            <footer class="submit-group">
              <div class="dropdown fr">
                <a href="" class="btn btn-blue btn-dropdown dropdown-toggle" data-toggle="dropdown">Save page&hellip;</a>
                <ul class="nav stacked dropdown-menu">
                    <li><a href="<?= ($pageName + 1) ?>.php">and Go to next page</a></li>
                    <li><a href="">and Mark as complete</a></li>
                    <li class="sep"></li>
                    <li><a class="disabled" href="">and Submit Survey</a></li>
                  </ul>              
              </div>
            </footer>

          </section>
          <!-- island End -->
        </div>
        <!-- Col9 end -->
        <?php include ( '../includes/_sidebar.php'); ?>
      <!-- Row End -->
      </div>
    </div>
    <!-- Modal Start -->  
<div id="modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <form action="">
    <div class="modal-header">
      <p class="modal-title">The Template Upload Process.</p>
      <a href="" class="close btn btn-yellow fr" data-dismiss="modal" aria-hidden="true">&times;</a>
    </div>
    <div class="modal-body">
  
        <div class="control-group full-width">
          <p>Describe template process.</p>
        </div>
    </div>
    <div class="modal-footer">
      <button class="btn btn-blue fr" data-dismiss="modal" aria-hidden="true">Close</button>
    </div>
  </form>
</div>
<!-- Modal End -->     

    <!-- Container End -->
<?php include ( '../includes/_footer.php'); ?>
